# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

install! 'cocoapods', :integrate_targets => false

target 'XplatformDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'

end
